# Generated by Django 5.0.2 on 2024-02-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='portafolio/icon-skill')),
                ('experiencia', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='label',
            field=models.CharField(choices=[('other', 'Other'), ('Django', 'Django'), ('React', 'React')], default='other', max_length=100),
        ),
    ]
