# Generated by Django 5.0.2 on 2024-03-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_tag_project_url_github_skill_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='label',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='tags',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='portfolio.tag'),
        ),
    ]
